version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: foodgram_db


  backend:
    image: amirkhan07/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    container_name: foodgram_backend

  frontend:
    image: amirkhan07/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend
    container_name: foodgram_nginx

volumes:
  static_value:
  media_value:
  db_data:
